Update Translator_style.py
When you face RuntimeError as follows, you may need to update the Translator_style.py.
```
Traceback (most recent call last):
File "translate.py", line 140, in <module> main() File "translate.py", line 66, in main translator = onmt.Translator_style(opt) File "/home/tyt/style-trans/Style-Transfer-Through-Back-Translation-master/style_decoder/onmt/Translator_style.py", line 22, in __init__ decoder.load_state_dict(checkpoint['decoder'])
File "/home/tyt/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named word_lut.weight, whose dimensions in the model are torch.Size([9603, 300]) and whose dimensions in the checkpoint are torch.Size([9603, 100]).
```